name: CI/CD Pipeline for Vue.js Frontend Dev

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Gunakan versi Node yang stabil, sesuaikan dengan kebutuhan proyek

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build Vue.js App with Vite
        run: npm run build

      - name: Debug Build Output
        run: ls -la dist/ || echo "Dist folder not found"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vue-build
          path: dist/
          retention-days: 1

      - name: Debug Artifact Upload
        run: echo "Artifact uploaded successfully" || echo "Artifact upload failed"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: vue-build
          path: dist/

      - name: Debug Downloaded Artifact
        run: ls -la dist/ || echo "Downloaded artifact folder not found"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 nredutech.com >> ~/.ssh/known_hosts

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 -i ~/.ssh/id_spkbansos u1737816@nredutech.com << 'EOF'
            if [ ! -d "/home/u1737816/public_html/layakin/frontend" ]; then
              mkdir -p /home/u1737816/public_html/layakin/frontend
            fi
            rm -rf /home/u1737816/public_html/layakin/frontend/*
            exit
          EOF
          scp -r -P 65002 dist/* u1737816@nredutech.com:/home/u1737816/public_html/layakin/frontend/